/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#f9f9ff",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#a8c8ff",
        "on-tertiary-container": "#ffd0a0",
        "on-primary-fixed": "#001b3c",
        "on-primary-fixed-variant": "#0d4785",
        "on-secondary-container": "#60646e",
        "on-surface": "#191c1f",
        "primary-fixed-dim": "#a8c8ff",
        "on-secondary-fixed-variant": "#434750",
        "inverse-surface": "#2e3035",
        "tertiary-fixed-dim": "#ffb868",
        "tertiary": "#673d00",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffddbb",
        "surface-container": "#ededf3",
        "on-error": "#ffffff",
        "secondary": "#5a5e68",
        "on-secondary-fixed": "#171c24",
        "secondary-fixed": "#dfe2ee",
        "surface-variant": "#424750",
        "on-background": "#1a1c20",
        "primary-container": "#305f9f",
        "surface-container-high": "#e8e8ee",
        "surface": "#f7f9fd",
        "on-tertiary-fixed": "#2b1700",
        "surface-dim": "#d9d9df",
        "shadow-light": "#ffffff",
        "secondary-fixed-dim": "#c3c6d1",
        "inverse-on-surface": "#f0f0f6",
        "on-surface-variant": "#424750",
        "outline": "#737781",
        "on-primary": "#ffffff",
        "surface-tint": "#305f9f",
        "surface-container-low": "#f3f3f9",
        "primary-fixed": "#d5e3ff",
        "on-secondary": "#ffffff",
        "shadow-dark": "#dce1eb",
        "outline-variant": "#c3c6d2",
        "secondary-container": "#dfe2ee",
        "on-error-container": "#93000a",
        "tertiary-container": "#885200",
        "on-primary-container": "#c6daff",
        "on-tertiary-fixed-variant": "#673d00",
        "surface-container-highest": "#e2e2e8",
        "surface-container-lowest": "#ffffff",
        "primary": "#0e4786",
        "surface-bright": "#f9f9ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-gap": "1rem",
        "margin-page": "2rem",
        "gutter": "1.5rem",
        "padding-card": "1.5rem"
      },
      fontFamily: {
        "label-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "code": ["JetBrains Mono"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-lg": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "code": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
